# Generated by Django 5.1.4 on 2025-01-22 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_category_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="place",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
