# Generated by Django 5.1.4 on 2025-01-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_place"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.FloatField(default=0, help_text="Discount percentage (0-100)"),
        ),
        migrations.AddField(
            model_name="product",
            name="special_mark",
            field=models.CharField(
                blank=True,
                help_text="Special mark for the product",
                max_length=200,
                null=True,
            ),
        ),
    ]
