# Generated by Django 5.1.4 on 2025-01-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_product_discount_product_special_mark"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
    ]
